version: '3.8'

services:
  db:
    image: postgres:14
    container_name: jobtrackerai-db
    restart: always
    environment:
      POSTGRES_DB: job_tracker_ai_db
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .  #build app using Dockerfile in current dir
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_SHOW-SQL: ${SPRING_JPA_SHOW_SQL}
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
      GEMINI_API_KEY: ${GEMINI_API_KEY}

    stdin_open: true  # Keeps the container running interactively
    tty: true


volumes:
  db_data:     # Defines a names volume called db_data which persists PostgreSQL data across container restarts
